# Generated by Django 4.2.1 on 2023-06-16 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinadores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinador',
            name='empleado',
            field=models.BooleanField(default=True),
        ),
    ]
