# Generated by Django 4.2.1 on 2023-06-20 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adicionales', '0001_initial'),
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='adicional',
            field=models.ManyToManyField(to='adicionales.adicional'),
        ),
    ]
