# Generated by Django 4.2.1 on 2023-06-20 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adicionales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adicional',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
