# Generated by Django 4.2.1 on 2023-06-17 22:30

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='empleado',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
