# Generated by Django 4.2.1 on 2023-06-18 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_alter_empleado_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='is_admin',
        ),
        migrations.AlterField(
            model_name='empleado',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
