# Generated by Django 4.2.1 on 2023-06-12 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='empleado',
            field=models.BooleanField(default=False),
        ),
    ]
